"""Semantic operation registry for the experimental TileSight API."""

from .legacy import LegacyCompatibilityPolicy
from .registry import (
    DEFAULT_OP_REGISTRY,
    OpDefinition,
    SemanticOpRegistry,
    default_registry,
    make_elementwise,
    make_gemm,
    make_reduce,
)
from .schema import (
    DTypeSpec,
    ElementwiseOpSpec,
    EngineSpec,
    GemmOpSpec,
    ReduceOpSpec,
    ReductionAxisSpec,
    ScalarWorkSpec,
    SemanticOpSpec,
    TensorOperandSpec,
    TensorResultSpec,
    as_dtype,
    as_engine,
    concrete_elements,
    is_semantic_op,
)
from .throughput import (
    ThroughputFallbackPolicy,
    ThroughputRequest,
    ThroughputResolution,
    UnsupportedThroughputError,
    WorkThroughputBinding,
    bind_work_throughputs,
    resolve_throughput,
)

__all__ = [
    "DEFAULT_OP_REGISTRY",
    "DTypeSpec",
    "ElementwiseOpSpec",
    "EngineSpec",
    "GemmOpSpec",
    "LegacyCompatibilityPolicy",
    "OpDefinition",
    "ReduceOpSpec",
    "ReductionAxisSpec",
    "ScalarWorkSpec",
    "SemanticOpRegistry",
    "SemanticOpSpec",
    "TensorOperandSpec",
    "TensorResultSpec",
    "ThroughputFallbackPolicy",
    "ThroughputRequest",
    "ThroughputResolution",
    "UnsupportedThroughputError",
    "WorkThroughputBinding",
    "as_dtype",
    "as_engine",
    "bind_work_throughputs",
    "concrete_elements",
    "default_registry",
    "is_semantic_op",
    "make_elementwise",
    "make_gemm",
    "make_reduce",
    "resolve_throughput",
]
