"""TileSight modeling interfaces and their underlying schedule machinery.

Use ``program.KernelBuilder`` and ``program.analyze`` for new tile programs.
The low-level frontend and compatibility adapters remain exported for internal
evaluation and baseline reproduction; usage examples live in ``program.examples``.
"""

from .errors import ModelingError, ModelingValidationError, TimingResolutionError
from .frontend import (
    Actor,
    Fusion,
    Kernel,
    Launch,
    Materialization,
    PeriodicLoop,
    legacy_level_path,
)
from .ir import (
    ActorIR,
    Buffer,
    Dependency,
    ExecutionDomain,
    Event,
    FusionPlan,
    Handoff,
    KernelIR,
    LaunchIR,
    Lifetime,
    LayoutMapping,
    MemoryAccess,
    Occurrence,
    OwnershipMap,
    PeriodicLoopIR,
    Phase,
    PipelineBuffer,
    ResourceTiming,
    ResourceSequenceIR,
    State,
    StateCarry,
    Timing,
    TensorValue,
    Work,
)
from .lowering import lower_periodic
from .full_model import (
    AliasInterference,
    FeasibilityStatus,
    FullModelError,
    FullModelOptions,
    FullModelResult,
    FusionReport,
    GridResult,
    IISummary,
    LivenessReport,
    LivenessInterval,
    MemoryTraffic,
    OccupancyResult,
    OwnershipAssessment,
    ScopeCapacityReport,
    StoragePeak,
    TimingBreakdown,
    ValueTrafficPath,
    model,
)
from .liveness import analyze_fusion, analyze_liveness
from .native_executor import (
    FusionAwareCostResolver,
    NativeGridResult,
    NativeModelError,
    NativeModelOptions,
    NativeModelResult,
    RegionEvaluation,
    ResourceTraceEntry,
    TraceRepeat,
    evaluate_region,
    model_native,
)
from .native_policy import (
    LegacyStageBoundary,
    LaunchTopology,
    SmallTileLatencyConfig,
    WaveCostContext,
)
from .ops import (
    DTypeSpec,
    ElementwiseOpSpec,
    EngineSpec,
    GemmOpSpec,
    LegacyCompatibilityPolicy,
    ReduceOpSpec,
    SemanticOpRegistry,
    ThroughputFallbackPolicy,
    UnsupportedThroughputError,
    bind_work_throughputs,
    make_elementwise,
    make_gemm,
    make_reduce,
)
from .adapters.general_gemm import (
    BoundGemmCostOracle,
    GeneralGemmOptions,
    GeneralGemmResult,
    bind_general_gemm,
    model_general_gemm,
)
from .adapters.b200_cta2_gemm import (
    B200Cta2ExecutionPlan,
    B200Cta2LegacyBoundOracle,
    B200Cta2NativeEvaluation,
    B200Cta2NativeOptions,
    Cta2OperandRoute,
    Cta2ParticipantFootprint,
    Cta2PhysicalTransfer,
    Cta2ProtocolCosts,
    model_b200_cta2_native,
)
from .oracle import CostOracle, StaticTimingOracle
from .regions import LoopRegion, PeriodicAxisIR, PhaseRegion, RegionIR, SequenceRegion
from .resident_schedule import (
    ResidentResourceRef,
    ResidentScheduleConfig,
    ResidentScheduleError,
    ResidentScheduleResult,
    ResidentScheduleWitness,
    ResourceScope,
    schedule_resident_ctas,
    verify_resident_witness,
)
from .units import ms, ns, second, us
from . import program
from .program import AnalysisResult, Context, KernelBuilder, Options, Program, analyze, compare, export_perfetto

__all__ = [
    "AnalysisResult",
    "Context",
    "KernelBuilder",
    "Options",
    "Program",
    "analyze",
    "compare",
    "export_perfetto",
    "program",
    "Actor",
    "ActorIR",
    "AliasInterference",
    "Buffer",
    "B200Cta2ExecutionPlan",
    "B200Cta2LegacyBoundOracle",
    "B200Cta2NativeEvaluation",
    "B200Cta2NativeOptions",
    "BoundGemmCostOracle",
    "CostOracle",
    "Cta2OperandRoute",
    "Cta2ParticipantFootprint",
    "Cta2PhysicalTransfer",
    "Cta2ProtocolCosts",
    "Dependency",
    "DTypeSpec",
    "ElementwiseOpSpec",
    "EngineSpec",
    "Event",
    "ExecutionDomain",
    "Fusion",
    "FusionPlan",
    "FeasibilityStatus",
    "FullModelError",
    "FullModelOptions",
    "FullModelResult",
    "FusionAwareCostResolver",
    "FusionReport",
    "GeneralGemmOptions",
    "GeneralGemmResult",
    "GemmOpSpec",
    "GridResult",
    "Handoff",
    "IISummary",
    "Kernel",
    "KernelIR",
    "Launch",
    "LaunchIR",
    "LaunchTopology",
    "LegacyCompatibilityPolicy",
    "LegacyStageBoundary",
    "Lifetime",
    "LayoutMapping",
    "LivenessReport",
    "LivenessInterval",
    "Materialization",
    "MemoryAccess",
    "MemoryTraffic",
    "ModelingError",
    "ModelingValidationError",
    "NativeGridResult",
    "NativeModelError",
    "NativeModelOptions",
    "NativeModelResult",
    "Occurrence",
    "OwnershipMap",
    "OwnershipAssessment",
    "OccupancyResult",
    "PeriodicLoop",
    "PeriodicLoopIR",
    "Phase",
    "PhaseRegion",
    "PipelineBuffer",
    "ResourceTiming",
    "ResourceSequenceIR",
    "ScopeCapacityReport",
    "ResourceTraceEntry",
    "RegionEvaluation",
    "RegionIR",
    "ReduceOpSpec",
    "ResidentResourceRef",
    "ResidentScheduleConfig",
    "ResidentScheduleError",
    "ResidentScheduleResult",
    "ResidentScheduleWitness",
    "ResourceScope",
    "LoopRegion",
    "PeriodicAxisIR",
    "SequenceRegion",
    "SemanticOpRegistry",
    "SmallTileLatencyConfig",
    "State",
    "StateCarry",
    "StoragePeak",
    "StaticTimingOracle",
    "Timing",
    "TimingResolutionError",
    "TimingBreakdown",
    "TraceRepeat",
    "ThroughputFallbackPolicy",
    "UnsupportedThroughputError",
    "WaveCostContext",
    "Work",
    "TensorValue",
    "ValueTrafficPath",
    "lower_periodic",
    "model",
    "analyze_fusion",
    "analyze_liveness",
    "bind_general_gemm",
    "bind_work_throughputs",
    "legacy_level_path",
    "evaluate_region",
    "model_native",
    "model_b200_cta2_native",
    "model_general_gemm",
    "make_elementwise",
    "make_gemm",
    "make_reduce",
    "ms",
    "ns",
    "second",
    "schedule_resident_ctas",
    "us",
    "verify_resident_witness",
]
